### PR TITLE
Misc customizations

### PR DESCRIPTION
**Pull request by booleanbetrayal**
Hi @asgeirrr - 

I found this tool to be a great starting point in doing some anonymization sweeps of my own. Thanks for the hard work! I did end up having to make several changes to support some general use-cases that might be useful to get upstream. Please take a look at these commits and let me know if I need to tweak anything before you'd consider merging. I haven't done any unit testing, so that'd probably have to be covered. Commits can be rebased as needed.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Hi @asgeirrr - Just checking in to see if you thought any of these commits were useful. Thanks!

**Comment by booleanbetrayal** [comment]
Sounds great. Thanks @asgeirrr . Hope you had a great vacation!

**Comment by colbymelvin** [comment]
This is super-duper-cool! Please merge!

**Comment by ragged** [comment]
Hey there, we would also like to use this tool, and wanted to ask if you are going to merge any time soon? If you need help just give a note. Will you maintain this at all in the future? 

regards

**Comment by booleanbetrayal** [comment]
Any thoughts on these changes yet @asgeirrr? Also, do you need help maintaining this repo? Don't mind carrying it forward if you don't have the time.

**Review by asgeirrr — APPROVED** [review]
Hello Brent and Rob, I'm sorry for not maintaining this repo for so long. I forgot about it and now got an email about another commit. I went through the changes and it looks good high-level so I'm gonna merge it. 

If you're interested, I can give you right to maintain this repository. It could use some love. It would be great e.g. to add unittests for your changes and do some general maintenance like update the dependencies etc.

**Comment by asgeirrr** [comment]
Hm, I'm gonna have to do some maintenance to the repo so it gets release to PyPI, everything is outdated.

**Pull request merged**
